/**
 * 3D grid math: the canonical 24 axis-aligned orientations, footprint
 * rotation, face transforms, occupancy keys, and centreline mirroring.
 * Pure functions, no engine dependencies.
 */

import type { Face, OrientationIndex, Vec3i } from './types.ts';
import { GRID_MAX, GRID_MIN } from './types.ts';

/** Row-major 3x3 integer matrix. */
export type Mat3 = readonly [
  number, number, number,
  number, number, number,
  number, number, number,
];

const IDENTITY: Mat3 = [1, 0, 0, 0, 1, 0, 0, 0, 1];
// 90° rotations about each axis (right-handed).
const RX: Mat3 = [1, 0, 0, 0, 0, -1, 0, 1, 0];
const RY: Mat3 = [0, 0, 1, 0, 1, 0, -1, 0, 0];
const RZ: Mat3 = [0, -1, 0, 1, 0, 0, 0, 0, 1];

function matMul(a: Mat3, b: Mat3): Mat3 {
  const r: number[] = new Array(9).fill(0);
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      let s = 0;
      for (let k = 0; k < 3; k++) s += a[i * 3 + k] * b[k * 3 + j];
      r[i * 3 + j] = s;
    }
  }
  return r as unknown as Mat3;
}

function matKey(m: Mat3): string {
  return m.join(',');
}

/** All 24 proper rotations, generated by BFS from identity. Index 0 is identity. */
export const ORIENTATIONS: readonly Mat3[] = (() => {
  const seen = new Map<string, Mat3>();
  const queue: Mat3[] = [IDENTITY];
  seen.set(matKey(IDENTITY), IDENTITY);
  while (queue.length > 0) {
    const m = queue.shift()!;
    for (const g of [RX, RY, RZ]) {
      const n = matMul(g, m);
      const k = matKey(n);
      if (!seen.has(k)) {
        seen.set(k, n);
        queue.push(n);
      }
    }
  }
  const all = [...seen.values()];
  // Deterministic order with identity first.
  all.sort((a, b) => (matKey(a) === matKey(IDENTITY) ? -1 : matKey(b) === matKey(IDENTITY) ? 1 : matKey(a).localeCompare(matKey(b))));
  if (all.length !== 24) throw new Error(`expected 24 orientations, got ${all.length}`);
  return all;
})();

export const ORIENTATION_COUNT = ORIENTATIONS.length;

const INDEX_BY_KEY = new Map<string, number>(ORIENTATIONS.map((m, i) => [matKey(m), i]));

export function orientationIndexOfMatrix(m: Mat3): OrientationIndex {
  const i = INDEX_BY_KEY.get(matKey(m));
  if (i === undefined) throw new Error(`matrix is not a valid orientation: ${matKey(m)}`);
  return i;
}

/** compose(a, b): apply b first, then a. */
export function composeOrientations(a: OrientationIndex, b: OrientationIndex): OrientationIndex {
  return orientationIndexOfMatrix(matMul(ORIENTATIONS[a], ORIENTATIONS[b]));
}

export function inverseOrientation(o: OrientationIndex): OrientationIndex {
  const m = ORIENTATIONS[o];
  // Rotation matrices: inverse = transpose.
  const t: Mat3 = [m[0], m[3], m[6], m[1], m[4], m[7], m[2], m[5], m[8]];
  return orientationIndexOfMatrix(t);
}

/** Orientation from successive 90° steps about X, then Y, then Z. */
export function orientationFromSteps(rx: number, ry: number, rz: number): OrientationIndex {
  let m: Mat3 = IDENTITY;
  const mod = (n: number) => ((n % 4) + 4) % 4;
  for (let i = 0; i < mod(rx); i++) m = matMul(RX, m);
  for (let i = 0; i < mod(ry); i++) m = matMul(RY, m);
  for (let i = 0; i < mod(rz); i++) m = matMul(RZ, m);
  return orientationIndexOfMatrix(m);
}

export function rotateVec(orient: OrientationIndex, v: Vec3i): Vec3i {
  const m = ORIENTATIONS[orient];
  return {
    x: m[0] * v.x + m[1] * v.y + m[2] * v.z,
    y: m[3] * v.x + m[4] * v.y + m[5] * v.z,
    z: m[6] * v.x + m[7] * v.y + m[8] * v.z,
  };
}

export const FACE_VECTORS: Record<Face, Vec3i> = {
  px: { x: 1, y: 0, z: 0 },
  nx: { x: -1, y: 0, z: 0 },
  py: { x: 0, y: 1, z: 0 },
  ny: { x: 0, y: -1, z: 0 },
  pz: { x: 0, y: 0, z: 1 },
  nz: { x: 0, y: 0, z: -1 },
};

export const ALL_FACES: readonly Face[] = ['px', 'nx', 'py', 'ny', 'pz', 'nz'];

export function faceFromVector(v: Vec3i): Face {
  for (const f of ALL_FACES) {
    const fv = FACE_VECTORS[f];
    if (fv.x === v.x && fv.y === v.y && fv.z === v.z) return f;
  }
  throw new Error(`not a unit axis vector: ${v.x},${v.y},${v.z}`);
}

export function oppositeFace(f: Face): Face {
  const map: Record<Face, Face> = { px: 'nx', nx: 'px', py: 'ny', ny: 'py', pz: 'nz', nz: 'pz' };
  return map[f];
}

export function rotateFace(orient: OrientationIndex, f: Face): Face {
  return faceFromVector(rotateVec(orient, FACE_VECTORS[f]));
}

export function addVec(a: Vec3i, b: Vec3i): Vec3i {
  return { x: a.x + b.x, y: a.y + b.y, z: a.z + b.z };
}

export function vecEquals(a: Vec3i, b: Vec3i): boolean {
  return a.x === b.x && a.y === b.y && a.z === b.z;
}

export function cellKey(c: Vec3i): string {
  return `${c.x},${c.y},${c.z}`;
}

export function cellInBounds(c: Vec3i): boolean {
  return (
    c.x >= GRID_MIN.x && c.x <= GRID_MAX.x &&
    c.y >= GRID_MIN.y && c.y <= GRID_MAX.y &&
    c.z >= GRID_MIN.z && c.z <= GRID_MAX.z
  );
}

/** World cells of a footprint placed at pos with orientation. */
export function worldCells(localCells: readonly Vec3i[], pos: Vec3i, orient: OrientationIndex): Vec3i[] {
  return localCells.map((c) => addVec(pos, rotateVec(orient, c)));
}

/**
 * Mirror an orientation across the vehicle centreline (X = 0 plane).
 * Conjugation by diag(-1,1,1) maps rotations to rotations.
 */
export function mirrorOrientationX(o: OrientationIndex): OrientationIndex {
  const m = ORIENTATIONS[o];
  // M * R * M where M = diag(-1,1,1): negate row 0 and column 0.
  const r: Mat3 = [m[0], -m[1], -m[2], -m[3], m[4], m[5], -m[6], m[7], m[8]];
  return orientationIndexOfMatrix(r);
}

export function mirrorCellX(c: Vec3i): Vec3i {
  return { x: -c.x, y: c.y, z: c.z };
}
